---
- name: Make sure nodejs_version is set correctly.
  assert:
    that: nodejs_version in [ "0.10", "0.12", "4.x" ]

- name: Ensure Node.js is installed.
  yum: 
    name: nodejs
    state: installed
    enablerepo: epel

- name: Ensure npm is installed.
  yum: 
    name: nodejs
    state: installed
    enablerepo: epel